[package]
name = "tdo"
version = "0.0.1"
authors = ["Felix Wittwer <dev@felixwittwer.de>", "Felix Döring <mail@felixdoering.com>"]

[dependencies]
clap = "2"
serde = "0.9.1"
serde_derive = "0.9.1"
serde_json = "0.9.1"
